FROM adoptopenjdk/openjdk17:alpine-jre

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged JAR file into the container at /app
COPY /home/azureuser/myagent/_work/1/s/target/demo-0.0.1-SNAPSHOT.war.original /app/springinitializer

# Expose the port that your Spring Boot application uses
EXPOSE 8080
