FROM openjdk:17-alpine



# Copy the packaged WAR file into the container at /app
COPY target/demo-0.0.1-SNAPSHOT.war.original /usr/local/tomcat/webapps/demos-0.0.1-SNAPSHOT.war
 

# Expose the port that your Spring Boot application uses
EXPOSE 8080

