apiVersion: v1
kind: Service
metadata:
  name: app1-clusterip-service
  labels:
    app: app1-demo
spec:
  type: ClusterIP
  selector:
    app: app1-demo
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-demo
  template:
    metadata:
      labels:
        app: app1-demo
    spec:
      containers:
        - name: app1-demo
          image: avinash1012/java-spring-initializer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
